name: Build Latest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout downloader
        uses: actions/checkout@v5
      - name: Build latest bundle
        run: source build.sh
      - name: Commit new bundle
        run: |
          git add revenge.bundle
          git config --global user.name 'Github Actions Bot'
          git config --global user.email 'programmer2514@users.noreply.github.com'
          git commit -am "Update Revenge Next bundle"
          git push
